# Generated by Django 5.2.8 on 2025-12-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_incidencia', models.CharField(help_text='Nombre de la categoría', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Incidencia',
                'verbose_name_plural': 'Categorías de Incidencias',
                'db_table': 'categoria_incidencias',
                'ordering': ['nombre_categoria_incidencia'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del condominio (formato: XX.XXX.XXX-X)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del condominio', max_length=140)),
                ('direccion', models.CharField(help_text='Dirección completa', max_length=255)),
                ('region', models.CharField(help_text='Región donde se ubica', max_length=50)),
                ('comuna', models.CharField(help_text='Comuna del condominio', max_length=50)),
                ('mail_contacto', models.EmailField(help_text='Correo de contacto', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la incidencia', max_length=160)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado de la incidencia', max_length=15)),
                ('ubicacion_latitud_reporte', models.CharField(blank=True, help_text='Latitud del reporte', max_length=50, null=True)),
                ('ubicacion_longitud_reporte', models.CharField(blank=True, help_text='Longitud del reporte', max_length=50, null=True)),
                ('direccion_condominio_incidencia', models.CharField(blank=True, help_text='Dirección asociada', max_length=180, null=True)),
                ('fecha_reporte', models.DateField(auto_now_add=True, help_text='Fecha del reporte')),
                ('fecha_cierre', models.DateField(blank=True, help_text='Fecha de cierre', null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', help_text='Prioridad asignada', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(help_text='Condominio asociado', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='mi_condominio.condominio')),
                ('tipo_incidencia', models.ForeignKey(help_text='Categoría de la incidencia', on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='mi_condominio.categoriaincidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
                'ordering': ['-fecha_reporte', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_archivo_evidencia', models.URLField(help_text='URL del archivo', max_length=500)),
                ('tipo_archivo_evidencia', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento'), ('AUDIO', 'Audio'), ('OTRO', 'Otro')], help_text='Tipo de evidencia', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(help_text='Incidencia asociada', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='mi_condominio.incidencia')),
            ],
            options={
                'verbose_name': 'Evidencia de Incidencia',
                'verbose_name_plural': 'Evidencias de Incidencias',
                'db_table': 'evidencias_incidencia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, help_text='Detalle del registro', null=True)),
                ('accion', models.TextField(blank=True, help_text='Acción ejecutada', null=True)),
                ('fecha_bitacora', models.DateField(auto_now_add=True, help_text='Fecha del registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(help_text='Incidencia asociada', on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='mi_condominio.incidencia')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacoras',
                'ordering': ['-fecha_bitacora'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reunion', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria'), ('INFORMATIVA', 'Informativa')], help_text='Tipo de reunión', max_length=15)),
                ('nombre_reunion', models.CharField(help_text='Nombre de la reunión', max_length=20)),
                ('fecha_reunion', models.DateField(help_text='Fecha programada')),
                ('lugar_reunion', models.CharField(blank=True, help_text='Lugar de realización', max_length=60, null=True)),
                ('motivo_reunion', models.TextField(blank=True, help_text='Motivo o temática', null=True)),
                ('acta_reunion_url', models.URLField(blank=True, help_text='URL del acta de la reunión', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(help_text='Condominio asociado', on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='mi_condominio.condominio')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'db_table': 'reuniones',
                'ordering': ['-fecha_reunion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del usuario', max_length=200)),
                ('apellido', models.CharField(help_text='Apellidos del usuario', max_length=200)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], help_text='Género del usuario', max_length=1, null=True)),
                ('rut', models.CharField(help_text='RUT del usuario', max_length=10, unique=True)),
                ('correo', models.EmailField(help_text='Correo del usuario', max_length=200, unique=True)),
                ('residencia', models.TextField(blank=True, help_text='Dirección de residencia', null=True)),
                ('contrasena_hash', models.CharField(help_text='Contraseña cifrada', max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('CONSERJE', 'Conserje')], help_text='Rol del usuario', max_length=10)),
                ('estado_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado de la cuenta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(help_text='Condominio asociado', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='mi_condominio.condominio')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['apellido', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='usuario_reporta',
            field=models.ForeignKey(help_text='Usuario que reporta', on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to='mi_condominio.usuario'),
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_amonestacion', models.CharField(choices=[('VERBAL', 'Verbal'), ('ESCRITA', 'Escrita'), ('MULTA', 'Multa'), ('SUSPENSION', 'Suspensión de servicios')], help_text='Tipo de amonestación', max_length=15)),
                ('motivo', models.CharField(choices=[('RUIDOS_MOLESTOS', 'Ruidos molestos'), ('USO_INDEBIDO_ESTACIONAMIENTOS', 'Uso indebido de estacionamientos'), ('DANO_BIEN_COMUN', 'Daño a bien común'), ('MAL_USO_AREA_COMUN', 'Mal uso de área común'), ('INCUMPLIMIENTO_NORMAS_SANITARIAS', 'Incumplimiento de normas sanitarias'), ('TENENCIA_IRRESPONSABLE', 'Tenencia irresponsable'), ('MAL_USO_DUCTOS_BASURA', 'Mal uso de ductos de basura'), ('ARRIENDO_ILEGAL', 'Arriendo ilegal'), ('INCUMPLIMIENTO_OBRAS_REMODELACIONES', 'Incumplimiento en obras y remodelaciones'), ('IMPEDIMENTO_LABORES_ADMINISTRATIVAS', 'Impedimento de labores administrativas'), ('SEGURIDAD', 'Seguridad'), ('OTRO', 'Otro motivo')], help_text='Motivo principal de la amonestación', max_length=40)),
                ('motivo_detalle', models.CharField(blank=True, help_text='Detalle adicional del motivo o especificar si seleccionó "Otro"', max_length=200, null=True)),
                ('fecha_amonestacion', models.DateField(help_text='Fecha aplicada')),
                ('nombre_amonestado', models.CharField(help_text='Nombre del sancionado', max_length=150)),
                ('apellidos_amonestado', models.CharField(help_text='Apellidos del sancionado', max_length=150)),
                ('rut_amonestado', models.CharField(help_text='RUT del sancionado', max_length=10)),
                ('numero_departamento', models.CharField(blank=True, help_text='Número de departamento', max_length=60, null=True)),
                ('fecha_limite_pago', models.DateField(blank=True, help_text='Fecha límite de pago', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_reporta', models.ForeignKey(help_text='Usuario que reporta', on_delete=django.db.models.deletion.PROTECT, related_name='amonestaciones_reportadas', to='mi_condominio.usuario')),
            ],
            options={
                'verbose_name': 'Amonestación',
                'verbose_name_plural': 'Amonestaciones',
                'db_table': 'amonestaciones',
                'ordering': ['-fecha_amonestacion'],
            },
        ),
    ]
