# Generated by Django 5.2.8 on 2025-12-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_condominio', '0002_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena_hash',
        ),
    ]
