# Generated by Django 5.2.8 on 2025-12-19 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_condominio', '0003_remove_usuario_contrasena_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título opcional para la sesión', max_length=255, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sesión está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='mi_condominio.usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=10)),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('tokens_usados', models.IntegerField(blank=True, help_text='Tokens consumidos en esta respuesta', null=True)),
                ('tool_calls', models.JSONField(blank=True, help_text='Llamadas a herramientas MCP realizadas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mi_condominio.chatsession')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
