# Generated by Django 5.2.8 on 2025-12-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_condominio', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciaincidencia',
            name='url_archivo_evidencia',
        ),
        migrations.AddField(
            model_name='evidenciaincidencia',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='Archivo de evidencia (imagen, video, documento, etc.)', max_length=500, null=True, upload_to='evidencias/%Y/%m/'),
        ),
    ]
