# Generated by Django 5.2.8 on 2025-12-20 04:20

import mi_condominio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_condominio', '0005_cambio_evidencia_url_a_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaincidencia',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='Archivo de evidencia (imagen, video, documento, etc.)', max_length=500, null=True, upload_to=mi_condominio.models.evidencia_upload_path),
        ),
    ]
