# Generated by Django 5.2.8 on 2025-12-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_condominio', '0006_cambio_ruta_evidencias_por_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la región (ej: RM, V, VIII)', max_length=5, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la región', max_length=100, unique=True)),
                ('numero_romano', models.CharField(blank=True, help_text='Número romano de la región (ej: I, II, III)', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'regiones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la comuna', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(help_text='Región a la que pertenece la comuna', on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='mi_condominio.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comunas',
                'ordering': ['region', 'nombre'],
                'unique_together': {('region', 'nombre')},
            },
        ),
    ]
