# Generated by Django 5.2.8 on 2025-12-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_condominio', '0007_region_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='comuna',
            field=models.ForeignKey(help_text='Comuna del condominio', on_delete=django.db.models.deletion.PROTECT, related_name='condominios', to='mi_condominio.comuna'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='region',
            field=models.ForeignKey(help_text='Región donde se ubica', on_delete=django.db.models.deletion.PROTECT, related_name='condominios', to='mi_condominio.region'),
        ),
    ]
